package auction;


/**
* auction/AuctionUserOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* Sunday, March 8, 2020 7:11:24 PM CDT
*/

public interface AuctionUserOperations 
{
  boolean offer_item (String user_id, String item_desc, float initial_price);
  boolean sell (String user_id);
  boolean bid (String user_id, float price);
  String view_high_bidder ();
  String view_bid_status ();
  String view_auction_status ();
} // interface AuctionUserOperations
