package auction;


/**
* auction/AuctionUser.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* Sunday, March 8, 2020 7:11:24 PM CDT
*/

public interface AuctionUser extends AuctionUserOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AuctionUser
