package auction;

/**
* auction/AuctionUserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* Sunday, March 8, 2020 7:11:24 PM CDT
*/

public final class AuctionUserHolder implements org.omg.CORBA.portable.Streamable
{
  public auction.AuctionUser value = null;

  public AuctionUserHolder ()
  {
  }

  public AuctionUserHolder (auction.AuctionUser initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = auction.AuctionUserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    auction.AuctionUserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return auction.AuctionUserHelper.type ();
  }

}
